# Generated by Django 4.2.27 on 2026-01-26 05:48

from django.db import migrations, models
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('news', '0005_category_news_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='AboutPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='Страница')),
                ('desc', django_ckeditor_5.fields.CKEditor5Field(verbose_name='Описание о нас')),
            ],
            options={
                'verbose_name_plural': 'О нас',
            },
        ),
    ]
