# Generated by Django 4.2.27 on 2026-01-30 04:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0003_sociallink'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='sociallink',
            options={'verbose_name': 'соцсеть', 'verbose_name_plural': 'Соцсети'},
        ),
        migrations.AddField(
            model_name='employee',
            name='image',
            field=models.ImageField(null=True, upload_to='employee/', verbose_name='Фото'),
        ),
    ]
