# Generated by Django 4.2.27 on 2026-01-30 04:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0004_alter_sociallink_options_employee_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='slug',
            field=models.SlugField(null=True, unique=True),
        ),
    ]
