# Generated by Django 4.2.27 on 2026-01-30 04:17

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0005_employee_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='employee',
            name='biography',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Описание о нас'),
        ),
    ]
