# Generated by Django 4.2.27 on 2026-02-02 05:19

from django.db import migrations
import django_ckeditor_5.fields


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0006_employee_biography'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='biography',
            field=django_ckeditor_5.fields.CKEditor5Field(null=True, verbose_name='Биография'),
        ),
    ]
