# Generated by Django 4.2.27 on 2026-02-04 05:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0007_alter_employee_biography'),
    ]

    operations = [
        migrations.CreateModel(
            name='Images',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=20, verbose_name='Название фото')),
                ('image', models.ImageField(upload_to='images/', verbose_name='Фото')),
                ('employee', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='about.employee')),
            ],
            options={
                'verbose_name': 'фото',
                'verbose_name_plural': 'Фото',
            },
        ),
    ]
