# Generated by Django 4.2.27 on 2026-02-04 05:43

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0008_images'),
    ]

    operations = [
        migrations.AlterField(
            model_name='images',
            name='employee',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='about.employee'),
        ),
    ]
