# Generated by Django 4.2.27 on 2026-02-02 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Contact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=50, verbose_name='Название страницы')),
                ('phone_number1', models.CharField(max_length=15, verbose_name='Номер телефона 1')),
                ('phone_number2', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона 2')),
                ('phone_number3', models.CharField(blank=True, max_length=15, null=True, verbose_name='Номер телефона 3')),
                ('email', models.CharField(max_length=100, verbose_name='Электронная почта')),
                ('map', models.TextField(verbose_name='Ссылка на карту')),
                ('time_to_work', models.CharField(help_text='C 10:00 до 20:00', max_length=100, verbose_name='Время работы')),
                ('social_whatsapp', models.CharField(blank=True, help_text='https://wa.me/996555232323', max_length=100, null=True, verbose_name='Ватцап')),
                ('social_telegram', models.CharField(blank=True, help_text='https://t.me/edzen12', max_length=100, null=True, verbose_name='Telegram')),
                ('social_instagram', models.CharField(blank=True, help_text='https://www.instagram.com/edzn.bey/', max_length=100, null=True, verbose_name='Instagram')),
            ],
            options={
                'verbose_name': 'контакт',
                'verbose_name_plural': 'Контакты',
            },
        ),
    ]
